# Generated by Django 5.1.1 on 2024-09-14 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0002_notifications'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='applications',
            options={'verbose_name': 'Application', 'verbose_name_plural': 'Applications'},
        ),
        migrations.DeleteModel(
            name='Notifications',
        ),
    ]
